/**
 * The scene a fresh Excalidraw instance opens with.
 *
 * It was one line of text, and the canary screenshot came out as a blank canvas
 * with a sentence clipped mid word: a picture that reads as a broken instance
 * rather than a seeded one. An empty whiteboard cannot show that seeding worked,
 * because an empty whiteboard is also what a failed seed looks like.
 *
 * Held as base64 of the JSON, not as a template literal, because it travels
 * through a TypeScript string into a shell heredoc into a file in the guest, and
 * every one of those layers has its own quoting rules. base64 has none.
 *
 * Written by BOTH the recipe (so a rebuilt snapshot carries it) and the fork
 * time postFork (so instances forked from the current snapshot carry it without
 * a rebuild). The two agree because they read this constant.
 */
export const WELCOME_SCENE_B64 =
  "eyJ0eXBlIjoiZXhjYWxpZHJhdyIsInZlcnNpb24iOjIsInNvdXJjZSI6ImJsaW5rIiwiZWxlbWVudHMiOlt7InR5cGUiOiJ0" +
  "ZXh0IiwidmVyc2lvbiI6MSwidmVyc2lvbk5vbmNlIjoxMDAwMDEsImlzRGVsZXRlZCI6ZmFsc2UsImlkIjoiYmxpbmstMDEi" +
  "LCJmaWxsU3R5bGUiOiJzb2xpZCIsInN0cm9rZVdpZHRoIjoyLCJzdHJva2VTdHlsZSI6InNvbGlkIiwicm91Z2huZXNzIjox" +
  "LCJvcGFjaXR5IjoxMDAsImFuZ2xlIjowLCJ4IjoxMjAsInkiOjkwLCJzdHJva2VDb2xvciI6IiMxZTFlMWUiLCJiYWNrZ3Jv" +
  "dW5kQ29sb3IiOiJ0cmFuc3BhcmVudCIsIndpZHRoIjo2MzEsImhlaWdodCI6MzUsInNlZWQiOjIwMDAwMSwiZ3JvdXBJZHMi" +
  "OltdLCJmcmFtZUlkIjpudWxsLCJyb3VuZG5lc3MiOm51bGwsImJvdW5kRWxlbWVudHMiOltdLCJ1cGRhdGVkIjoxLCJsaW5r" +
  "IjpudWxsLCJsb2NrZWQiOmZhbHNlLCJ0ZXh0IjoiQmxpbms6IHdoYXQgaGFwcGVucyB3aGVuIHlvdSBwcmVzcyBMYXVuY2gi" +
  "LCJvcmlnaW5hbFRleHQiOiJCbGluazogd2hhdCBoYXBwZW5zIHdoZW4geW91IHByZXNzIExhdW5jaCIsImZvbnRTaXplIjoy" +
  "OCwiZm9udEZhbWlseSI6MSwidGV4dEFsaWduIjoibGVmdCIsInZlcnRpY2FsQWxpZ24iOiJ0b3AiLCJjb250YWluZXJJZCI6" +
  "bnVsbCwibGluZUhlaWdodCI6MS4yNX0seyJ0eXBlIjoicmVjdGFuZ2xlIiwidmVyc2lvbiI6MSwidmVyc2lvbk5vbmNlIjox" +
  "MDAwMDIsImlzRGVsZXRlZCI6ZmFsc2UsImlkIjoiYmxpbmstMDIiLCJmaWxsU3R5bGUiOiJzb2xpZCIsInN0cm9rZVdpZHRo" +
  "IjoyLCJzdHJva2VTdHlsZSI6InNvbGlkIiwicm91Z2huZXNzIjoxLCJvcGFjaXR5IjoxMDAsImFuZ2xlIjowLCJ4IjoxMjAs" +
  "InkiOjE3MCwic3Ryb2tlQ29sb3IiOiIjMWUxZTFlIiwiYmFja2dyb3VuZENvbG9yIjoiI2QzZjlkOCIsIndpZHRoIjoyMDAs" +
  "ImhlaWdodCI6OTAsInNlZWQiOjIwMDAwMiwiZ3JvdXBJZHMiOltdLCJmcmFtZUlkIjpudWxsLCJyb3VuZG5lc3MiOnsidHlw" +
  "ZSI6M30sImJvdW5kRWxlbWVudHMiOltdLCJ1cGRhdGVkIjoxLCJsaW5rIjpudWxsLCJsb2NrZWQiOmZhbHNlfSx7InR5cGUi" +
  "OiJ0ZXh0IiwidmVyc2lvbiI6MSwidmVyc2lvbk5vbmNlIjoxMDAwMDMsImlzRGVsZXRlZCI6ZmFsc2UsImlkIjoiYmxpbmst" +
  "MDMiLCJmaWxsU3R5bGUiOiJzb2xpZCIsInN0cm9rZVdpZHRoIjoyLCJzdHJva2VTdHlsZSI6InNvbGlkIiwicm91Z2huZXNz" +
  "IjoxLCJvcGFjaXR5IjoxMDAsImFuZ2xlIjowLCJ4IjoxNDUsInkiOjIwMCwic3Ryb2tlQ29sb3IiOiIjMWUxZTFlIiwiYmFj" +
  "a2dyb3VuZENvbG9yIjoidHJhbnNwYXJlbnQiLCJ3aWR0aCI6MTQwLCJoZWlnaHQiOjIwLCJzZWVkIjoyMDAwMDMsImdyb3Vw" +
  "SWRzIjpbXSwiZnJhbWVJZCI6bnVsbCwicm91bmRuZXNzIjpudWxsLCJib3VuZEVsZW1lbnRzIjpbXSwidXBkYXRlZCI6MSwi" +
  "bGluayI6bnVsbCwibG9ja2VkIjpmYWxzZSwidGV4dCI6IjEuIEZvcmsgc25hcHNob3QiLCJvcmlnaW5hbFRleHQiOiIxLiBG" +
  "b3JrIHNuYXBzaG90IiwiZm9udFNpemUiOjE2LCJmb250RmFtaWx5IjoxLCJ0ZXh0QWxpZ24iOiJsZWZ0IiwidmVydGljYWxB" +
  "bGlnbiI6InRvcCIsImNvbnRhaW5lcklkIjpudWxsLCJsaW5lSGVpZ2h0IjoxLjI1fSx7InR5cGUiOiJyZWN0YW5nbGUiLCJ2" +
  "ZXJzaW9uIjoxLCJ2ZXJzaW9uTm9uY2UiOjEwMDAwNCwiaXNEZWxldGVkIjpmYWxzZSwiaWQiOiJibGluay0wNCIsImZpbGxT" +
  "dHlsZSI6InNvbGlkIiwic3Ryb2tlV2lkdGgiOjIsInN0cm9rZVN0eWxlIjoic29saWQiLCJyb3VnaG5lc3MiOjEsIm9wYWNp" +
  "dHkiOjEwMCwiYW5nbGUiOjAsIngiOjM5MCwieSI6MTcwLCJzdHJva2VDb2xvciI6IiMxZTFlMWUiLCJiYWNrZ3JvdW5kQ29s" +
  "b3IiOiIjZDBlYmZmIiwid2lkdGgiOjIwMCwiaGVpZ2h0Ijo5MCwic2VlZCI6MjAwMDA0LCJncm91cElkcyI6W10sImZyYW1l" +
  "SWQiOm51bGwsInJvdW5kbmVzcyI6eyJ0eXBlIjozfSwiYm91bmRFbGVtZW50cyI6W10sInVwZGF0ZWQiOjEsImxpbmsiOm51" +
  "bGwsImxvY2tlZCI6ZmFsc2V9LHsidHlwZSI6InRleHQiLCJ2ZXJzaW9uIjoxLCJ2ZXJzaW9uTm9uY2UiOjEwMDAwNSwiaXNE" +
  "ZWxldGVkIjpmYWxzZSwiaWQiOiJibGluay0wNSIsImZpbGxTdHlsZSI6InNvbGlkIiwic3Ryb2tlV2lkdGgiOjIsInN0cm9r" +
  "ZVN0eWxlIjoic29saWQiLCJyb3VnaG5lc3MiOjEsIm9wYWNpdHkiOjEwMCwiYW5nbGUiOjAsIngiOjQyMCwieSI6MjAwLCJz" +
  "dHJva2VDb2xvciI6IiMxZTFlMWUiLCJiYWNrZ3JvdW5kQ29sb3IiOiJ0cmFuc3BhcmVudCIsIndpZHRoIjoxMzIsImhlaWdo" +
  "dCI6MjAsInNlZWQiOjIwMDAwNSwiZ3JvdXBJZHMiOltdLCJmcmFtZUlkIjpudWxsLCJyb3VuZG5lc3MiOm51bGwsImJvdW5k" +
  "RWxlbWVudHMiOltdLCJ1cGRhdGVkIjoxLCJsaW5rIjpudWxsLCJsb2NrZWQiOmZhbHNlLCJ0ZXh0IjoiMi4gSGVhbHRoIGNo" +
  "ZWNrIiwib3JpZ2luYWxUZXh0IjoiMi4gSGVhbHRoIGNoZWNrIiwiZm9udFNpemUiOjE2LCJmb250RmFtaWx5IjoxLCJ0ZXh0" +
  "QWxpZ24iOiJsZWZ0IiwidmVydGljYWxBbGlnbiI6InRvcCIsImNvbnRhaW5lcklkIjpudWxsLCJsaW5lSGVpZ2h0IjoxLjI1" +
  "fSx7InR5cGUiOiJyZWN0YW5nbGUiLCJ2ZXJzaW9uIjoxLCJ2ZXJzaW9uTm9uY2UiOjEwMDAwNiwiaXNEZWxldGVkIjpmYWxz" +
  "ZSwiaWQiOiJibGluay0wNiIsImZpbGxTdHlsZSI6InNvbGlkIiwic3Ryb2tlV2lkdGgiOjIsInN0cm9rZVN0eWxlIjoic29s" +
  "aWQiLCJyb3VnaG5lc3MiOjEsIm9wYWNpdHkiOjEwMCwiYW5nbGUiOjAsIngiOjY2MCwieSI6MTcwLCJzdHJva2VDb2xvciI6" +
  "IiMxZTFlMWUiLCJiYWNrZ3JvdW5kQ29sb3IiOiIjZmZlYzk5Iiwid2lkdGgiOjIwMCwiaGVpZ2h0Ijo5MCwic2VlZCI6MjAw" +
  "MDA2LCJncm91cElkcyI6W10sImZyYW1lSWQiOm51bGwsInJvdW5kbmVzcyI6eyJ0eXBlIjozfSwiYm91bmRFbGVtZW50cyI6" +
  "W10sInVwZGF0ZWQiOjEsImxpbmsiOm51bGwsImxvY2tlZCI6ZmFsc2V9LHsidHlwZSI6InRleHQiLCJ2ZXJzaW9uIjoxLCJ2" +
  "ZXJzaW9uTm9uY2UiOjEwMDAwNywiaXNEZWxldGVkIjpmYWxzZSwiaWQiOiJibGluay0wNyIsImZpbGxTdHlsZSI6InNvbGlk" +
  "Iiwic3Ryb2tlV2lkdGgiOjIsInN0cm9rZVN0eWxlIjoic29saWQiLCJyb3VnaG5lc3MiOjEsIm9wYWNpdHkiOjEwMCwiYW5n" +
  "bGUiOjAsIngiOjY5NSwieSI6MjAwLCJzdHJva2VDb2xvciI6IiMxZTFlMWUiLCJiYWNrZ3JvdW5kQ29sb3IiOiJ0cmFuc3Bh" +
  "cmVudCIsIndpZHRoIjoxMTQsImhlaWdodCI6MjAsInNlZWQiOjIwMDAwNywiZ3JvdXBJZHMiOltdLCJmcmFtZUlkIjpudWxs" +
  "LCJyb3VuZG5lc3MiOm51bGwsImJvdW5kRWxlbWVudHMiOltdLCJ1cGRhdGVkIjoxLCJsaW5rIjpudWxsLCJsb2NrZWQiOmZh" +
  "bHNlLCJ0ZXh0IjoiMy4gcHJldmlld1VybCIsIm9yaWdpbmFsVGV4dCI6IjMuIHByZXZpZXdVcmwiLCJmb250U2l6ZSI6MTYs" +
  "ImZvbnRGYW1pbHkiOjEsInRleHRBbGlnbiI6ImxlZnQiLCJ2ZXJ0aWNhbEFsaWduIjoidG9wIiwiY29udGFpbmVySWQiOm51" +
  "bGwsImxpbmVIZWlnaHQiOjEuMjV9LHsidHlwZSI6ImFycm93IiwidmVyc2lvbiI6MSwidmVyc2lvbk5vbmNlIjoxMDAwMDgs" +
  "ImlzRGVsZXRlZCI6ZmFsc2UsImlkIjoiYmxpbmstMDgiLCJmaWxsU3R5bGUiOiJzb2xpZCIsInN0cm9rZVdpZHRoIjoyLCJz" +
  "dHJva2VTdHlsZSI6InNvbGlkIiwicm91Z2huZXNzIjoxLCJvcGFjaXR5IjoxMDAsImFuZ2xlIjowLCJ4IjozMjUsInkiOjIx" +
  "NSwic3Ryb2tlQ29sb3IiOiIjMWUxZTFlIiwiYmFja2dyb3VuZENvbG9yIjoidHJhbnNwYXJlbnQiLCJ3aWR0aCI6NjAsImhl" +
  "aWdodCI6MCwic2VlZCI6MjAwMDA4LCJncm91cElkcyI6W10sImZyYW1lSWQiOm51bGwsInJvdW5kbmVzcyI6eyJ0eXBlIjoy" +
  "fSwiYm91bmRFbGVtZW50cyI6W10sInVwZGF0ZWQiOjEsImxpbmsiOm51bGwsImxvY2tlZCI6ZmFsc2UsInBvaW50cyI6W1sw" +
  "LDBdLFs2MCwwXV0sImVuZEFycm93aGVhZCI6ImFycm93Iiwic3RhcnRBcnJvd2hlYWQiOm51bGx9LHsidHlwZSI6ImFycm93" +
  "IiwidmVyc2lvbiI6MSwidmVyc2lvbk5vbmNlIjoxMDAwMDksImlzRGVsZXRlZCI6ZmFsc2UsImlkIjoiYmxpbmstMDkiLCJm" +
  "aWxsU3R5bGUiOiJzb2xpZCIsInN0cm9rZVdpZHRoIjoyLCJzdHJva2VTdHlsZSI6InNvbGlkIiwicm91Z2huZXNzIjoxLCJv" +
  "cGFjaXR5IjoxMDAsImFuZ2xlIjowLCJ4Ijo1OTUsInkiOjIxNSwic3Ryb2tlQ29sb3IiOiIjMWUxZTFlIiwiYmFja2dyb3Vu" +
  "ZENvbG9yIjoidHJhbnNwYXJlbnQiLCJ3aWR0aCI6NjAsImhlaWdodCI6MCwic2VlZCI6MjAwMDA5LCJncm91cElkcyI6W10s" +
  "ImZyYW1lSWQiOm51bGwsInJvdW5kbmVzcyI6eyJ0eXBlIjoyfSwiYm91bmRFbGVtZW50cyI6W10sInVwZGF0ZWQiOjEsImxp" +
  "bmsiOm51bGwsImxvY2tlZCI6ZmFsc2UsInBvaW50cyI6W1swLDBdLFs2MCwwXV0sImVuZEFycm93aGVhZCI6ImFycm93Iiwi" +
  "c3RhcnRBcnJvd2hlYWQiOm51bGx9LHsidHlwZSI6InJlY3RhbmdsZSIsInZlcnNpb24iOjEsInZlcnNpb25Ob25jZSI6MTAw" +
  "MDEwLCJpc0RlbGV0ZWQiOmZhbHNlLCJpZCI6ImJsaW5rLTEwIiwiZmlsbFN0eWxlIjoic29saWQiLCJzdHJva2VXaWR0aCI6" +
  "Miwic3Ryb2tlU3R5bGUiOiJzb2xpZCIsInJvdWdobmVzcyI6MSwib3BhY2l0eSI6MTAwLCJhbmdsZSI6MCwieCI6MzkwLCJ5" +
  "IjozMzAsInN0cm9rZUNvbG9yIjoiIzFlMWUxZSIsImJhY2tncm91bmRDb2xvciI6IiNmZmQ4YTgiLCJ3aWR0aCI6MjAwLCJo" +
  "ZWlnaHQiOjkwLCJzZWVkIjoyMDAwMTAsImdyb3VwSWRzIjpbXSwiZnJhbWVJZCI6bnVsbCwicm91bmRuZXNzIjp7InR5cGUi" +
  "OjN9LCJib3VuZEVsZW1lbnRzIjpbXSwidXBkYXRlZCI6MSwibGluayI6bnVsbCwibG9ja2VkIjpmYWxzZX0seyJ0eXBlIjoi" +
  "dGV4dCIsInZlcnNpb24iOjEsInZlcnNpb25Ob25jZSI6MTAwMDExLCJpc0RlbGV0ZWQiOmZhbHNlLCJpZCI6ImJsaW5rLTEx" +
  "IiwiZmlsbFN0eWxlIjoic29saWQiLCJzdHJva2VXaWR0aCI6Miwic3Ryb2tlU3R5bGUiOiJzb2xpZCIsInJvdWdobmVzcyI6" +
  "MSwib3BhY2l0eSI6MTAwLCJhbmdsZSI6MCwieCI6NDEyLCJ5IjozNjAsInN0cm9rZUNvbG9yIjoiIzFlMWUxZSIsImJhY2tn" +
  "cm91bmRDb2xvciI6InRyYW5zcGFyZW50Iiwid2lkdGgiOjE0MCwiaGVpZ2h0IjoyMCwic2VlZCI6MjAwMDExLCJncm91cElk" +
  "cyI6W10sImZyYW1lSWQiOm51bGwsInJvdW5kbmVzcyI6bnVsbCwiYm91bmRFbGVtZW50cyI6W10sInVwZGF0ZWQiOjEsImxp" +
  "bmsiOm51bGwsImxvY2tlZCI6ZmFsc2UsInRleHQiOiI0LiBZb3VycywgMTAgbWluIiwib3JpZ2luYWxUZXh0IjoiNC4gWW91" +
  "cnMsIDEwIG1pbiIsImZvbnRTaXplIjoxNiwiZm9udEZhbWlseSI6MSwidGV4dEFsaWduIjoibGVmdCIsInZlcnRpY2FsQWxp" +
  "Z24iOiJ0b3AiLCJjb250YWluZXJJZCI6bnVsbCwibGluZUhlaWdodCI6MS4yNX0seyJ0eXBlIjoiYXJyb3ciLCJ2ZXJzaW9u" +
  "IjoxLCJ2ZXJzaW9uTm9uY2UiOjEwMDAxMiwiaXNEZWxldGVkIjpmYWxzZSwiaWQiOiJibGluay0xMiIsImZpbGxTdHlsZSI6" +
  "InNvbGlkIiwic3Ryb2tlV2lkdGgiOjIsInN0cm9rZVN0eWxlIjoic29saWQiLCJyb3VnaG5lc3MiOjEsIm9wYWNpdHkiOjEw" +
  "MCwiYW5nbGUiOjAsIngiOjQ5MCwieSI6MjY1LCJzdHJva2VDb2xvciI6IiMxZTFlMWUiLCJiYWNrZ3JvdW5kQ29sb3IiOiJ0" +
  "cmFuc3BhcmVudCIsIndpZHRoIjowLCJoZWlnaHQiOjYwLCJzZWVkIjoyMDAwMTIsImdyb3VwSWRzIjpbXSwiZnJhbWVJZCI6" +
  "bnVsbCwicm91bmRuZXNzIjp7InR5cGUiOjJ9LCJib3VuZEVsZW1lbnRzIjpbXSwidXBkYXRlZCI6MSwibGluayI6bnVsbCwi" +
  "bG9ja2VkIjpmYWxzZSwicG9pbnRzIjpbWzAsMF0sWzAsNjBdXSwiZW5kQXJyb3doZWFkIjoiYXJyb3ciLCJzdGFydEFycm93" +
  "aGVhZCI6bnVsbH0seyJ0eXBlIjoidGV4dCIsInZlcnNpb24iOjEsInZlcnNpb25Ob25jZSI6MTAwMDEzLCJpc0RlbGV0ZWQi" +
  "OmZhbHNlLCJpZCI6ImJsaW5rLTEzIiwiZmlsbFN0eWxlIjoic29saWQiLCJzdHJva2VXaWR0aCI6Miwic3Ryb2tlU3R5bGUi" +
  "OiJzb2xpZCIsInJvdWdobmVzcyI6MSwib3BhY2l0eSI6MTAwLCJhbmdsZSI6MCwieCI6MTIwLCJ5Ijo0NzAsInN0cm9rZUNv" +
  "bG9yIjoiIzFlMWUxZSIsImJhY2tncm91bmRDb2xvciI6InRyYW5zcGFyZW50Iiwid2lkdGgiOjYyMCwiaGVpZ2h0IjoyNSwi" +
  "c2VlZCI6MjAwMDEzLCJncm91cElkcyI6W10sImZyYW1lSWQiOm51bGwsInJvdW5kbmVzcyI6bnVsbCwiYm91bmRFbGVtZW50" +
  "cyI6W10sInVwZGF0ZWQiOjEsImxpbmsiOm51bGwsImxvY2tlZCI6ZmFsc2UsInRleHQiOiJUaGlzIGNhbnZhcyBpcyB5b3Vy" +
  "cy4gSXQgZGlzYXBwZWFycyB3aGVuIHlvdSBsZWF2ZS4iLCJvcmlnaW5hbFRleHQiOiJUaGlzIGNhbnZhcyBpcyB5b3Vycy4g" +
  "SXQgZGlzYXBwZWFycyB3aGVuIHlvdSBsZWF2ZS4iLCJmb250U2l6ZSI6MjAsImZvbnRGYW1pbHkiOjEsInRleHRBbGlnbiI6" +
  "ImxlZnQiLCJ2ZXJ0aWNhbEFsaWduIjoidG9wIiwiY29udGFpbmVySWQiOm51bGwsImxpbmVIZWlnaHQiOjEuMjV9LHsidHlw" +
  "ZSI6InRleHQiLCJ2ZXJzaW9uIjoxLCJ2ZXJzaW9uTm9uY2UiOjEwMDAxNCwiaXNEZWxldGVkIjpmYWxzZSwiaWQiOiJibGlu" +
  "ay0xNCIsImZpbGxTdHlsZSI6InNvbGlkIiwic3Ryb2tlV2lkdGgiOjIsInN0cm9rZVN0eWxlIjoic29saWQiLCJyb3VnaG5l" +
  "c3MiOjEsIm9wYWNpdHkiOjEwMCwiYW5nbGUiOjAsIngiOjEyMCwieSI6NTA1LCJzdHJva2VDb2xvciI6IiM4NjhlOTYiLCJi" +
  "YWNrZ3JvdW5kQ29sb3IiOiJ0cmFuc3BhcmVudCIsIndpZHRoIjo2MjAsImhlaWdodCI6MjUsInNlZWQiOjIwMDAxNCwiZ3Jv" +
  "dXBJZHMiOltdLCJmcmFtZUlkIjpudWxsLCJyb3VuZG5lc3MiOm51bGwsImJvdW5kRWxlbWVudHMiOltdLCJ1cGRhdGVkIjox" +
  "LCJsaW5rIjpudWxsLCJsb2NrZWQiOmZhbHNlLCJ0ZXh0IjoiRHJhdyBvbiBpdC4gTm90aGluZyBoZXJlIGlzIHNoYXJlZCB3" +
  "aXRoIGFueW9uZSBlbHNlLiIsIm9yaWdpbmFsVGV4dCI6IkRyYXcgb24gaXQuIE5vdGhpbmcgaGVyZSBpcyBzaGFyZWQgd2l0" +
  "aCBhbnlvbmUgZWxzZS4iLCJmb250U2l6ZSI6MjAsImZvbnRGYW1pbHkiOjEsInRleHRBbGlnbiI6ImxlZnQiLCJ2ZXJ0aWNh" +
  "bEFsaWduIjoidG9wIiwiY29udGFpbmVySWQiOm51bGwsImxpbmVIZWlnaHQiOjEuMjV9XSwiYXBwU3RhdGUiOnsidmlld0Jh" +
  "Y2tncm91bmRDb2xvciI6IiNmZmZmZmYiLCJncmlkU2l6ZSI6bnVsbCwic2Nyb2xsWCI6MCwic2Nyb2xsWSI6MCwiem9vbSI6" +
  "eyJ2YWx1ZSI6MX19LCJmaWxlcyI6e319";

/** Asserted by the recipe and by the fork time write, so a truncated copy fails loudly. */
export const WELCOME_SCENE_ELEMENTS = 14;

/** Present in the scene text. The recipe greps for it as a content check. */
export const WELCOME_SCENE_MARKER = "This canvas is yours";
