/**
 * G8: does a REAL browser's WebSocket survive Uptime Kuma's origin check
 * behind `previewUrl`? (Q20)
 *
 * V68 established that the preview domain carries WebSocket upgrades. It did not
 * establish that a browser is admitted, and the distinction is the whole point
 * of this gate.
 *
 * Uptime Kuma 2.x `allowRequest` (server/uptime-kuma-server.js):
 *
 *   - polling            -> allowed unconditionally
 *   - websocket, no Origin header -> allowed, explicitly
 *   - websocket with Origin -> requires origin.host === req.headers.host
 *
 * Node's `WebSocket` sends no Origin and offers no way to set one, so V68's pass
 * took the second branch. **The check that would reject a browser is the one
 * that probe could not trigger.** A browser always sends Origin, so whether a
 * visitor is admitted depends on whether the preview proxy presents Host and
 * Origin consistently to the guest, which nothing has measured.
 *
 * So this gate opens a real Solari browser, navigates it to the previewUrl so
 * the page origin IS the preview host, and opens the WebSocket from inside that
 * page. The Origin header is then generated by Chromium, not by us, which is the
 * only way to test the branch that matters.
 *
 * The bypass flag `UPTIME_KUMA_WS_ORIGIN_CHECK=bypass` is deliberately NOT used.
 * If a real browser is rejected, that is a finding about running this app behind
 * a preview domain, and it belongs in the docs and in a note to Solari rather
 * than being switched off. Turning off a cross-site websocket hijacking defence
 * to make a demo work is how a demo becomes the reason for an incident.
 */

import { Solari } from "@solarisdk/browser";

import { estimate } from "./lib/cost.ts";

import { registerSecret, handleFor } from "../../src/redact.ts";

import { safeErr, safeOut } from "../../src/safe-io.ts";
import { SIZE_SMALL } from "../../src/guard/rates.ts";
import { loadRegistry, APPS } from "./lib/apps.ts";
import { waitHealthyInGuest } from "./lib/health.ts";
import type { GateContext, GateDefinition } from "./lib/harness.ts";
import { runGate } from "./lib/harness.ts";

const KUMA_PORT = APPS.uptimekuma!.port;

/**
 * Run inside the page, at the preview origin.
 *
 * Returns the first engine.io frame, or the failure. Chromium supplies the
 * Origin header for this socket because the page was loaded from that origin,
 * which is exactly what a visitor's browser does and what Node cannot imitate.
 */
const PROBE_JS = `
(() => new Promise((resolve) => {
  try {
    const u = new URL(location.href);
    u.protocol = u.protocol === "https:" ? "wss:" : "ws:";
    u.pathname = "/socket.io/";
    u.searchParams.set("EIO", "4");
    u.searchParams.set("transport", "websocket");
    const ws = new WebSocket(u.toString());
    const t = setTimeout(() => resolve(JSON.stringify({ ok: false, why: "timeout waiting for first frame" })), 15000);
    ws.onmessage = (ev) => {
      clearTimeout(t);
      const d = String(ev.data || "");
      resolve(JSON.stringify({ ok: d.startsWith("0"), why: d.startsWith("0") ? "OPEN packet" : "first frame not OPEN", frame: d.slice(0, 120), origin: location.origin }));
      try { ws.close(); } catch {}
    };
    ws.onerror = () => { clearTimeout(t); resolve(JSON.stringify({ ok: false, why: "socket error", origin: location.origin })); };
    ws.onclose = (e) => { clearTimeout(t); resolve(JSON.stringify({ ok: false, why: "closed before OPEN, code " + e.code, origin: location.origin })); };
  } catch (e) { resolve(JSON.stringify({ ok: false, why: "threw: " + e.message })); }
}))()
`;

type Probe = { ok: boolean; why: string; frame?: string; origin?: string };

async function probeInBrowser(cdpEndpoint: string, pageUrl: string): Promise<Probe> {
  const ws = new WebSocket(cdpEndpoint);
  try {
    await new Promise<void>((resolve, reject) => {
      const t = setTimeout(() => reject(new Error("cdp connect timeout")), 20_000);
      ws.addEventListener("open", () => { clearTimeout(t); resolve(); });
      ws.addEventListener("error", () => { clearTimeout(t); reject(new Error("cdp connect error")); });
    });

    let id = 0;
    let pageSessionId: string | undefined;
    const pending = new Map<number, (v: unknown) => void>();
    const call = (method: string, params: Record<string, unknown> = {}) =>
      new Promise<unknown>((resolve, reject) => {
        id += 1;
        const msg: Record<string, unknown> = { id, method, params };
        if (pageSessionId && (method.startsWith("Page.") || method.startsWith("Runtime."))) msg.sessionId = pageSessionId;
        const myId = id;
        const timer = setTimeout(() => { pending.delete(myId); reject(new Error(`${method} timed out`)); }, 30_000);
        pending.set(myId, (v) => { clearTimeout(timer); resolve(v); });
        ws.send(JSON.stringify(msg));
      });

    ws.addEventListener("message", (ev) => {
      const raw = typeof ev.data === "string" ? ev.data : "";
      if (!raw) return;
      let msg: { id?: number; result?: unknown; error?: { message?: string } };
      try { msg = JSON.parse(raw); } catch { return; }
      if (msg.id !== undefined && pending.has(msg.id)) {
        const done = pending.get(msg.id)!;
        pending.delete(msg.id);
        done(msg.error ? { __error: msg.error.message } : (msg.result ?? {}));
      }
    });

    // Browser-level endpoint: create a page target and attach flat, as G5 learned.
    const created = await call("Target.createTarget", { url: "about:blank" }) as { targetId?: string };
    if (!created.targetId) throw new Error("Target.createTarget returned no targetId");
    const attached = await call("Target.attachToTarget", { targetId: created.targetId, flatten: true }) as { sessionId?: string };
    if (!attached.sessionId) throw new Error("Target.attachToTarget returned no sessionId");
    pageSessionId = attached.sessionId;

    await call("Page.enable");
    await call("Runtime.enable");
    // Navigate FIRST. The page must be loaded from the preview origin, or the
    // WebSocket it opens carries the wrong Origin and this gate measures nothing.
    await call("Page.navigate", { url: pageUrl });
    await new Promise((r) => setTimeout(r, 4000));

    const evald = await call("Runtime.evaluate", {
      expression: PROBE_JS, awaitPromise: true, returnByValue: true,
    }) as { result?: { value?: string }; __error?: string };
    if (evald.__error) return { ok: false, why: `Runtime.evaluate failed: ${evald.__error}` };
    const value = evald.result?.value;
    if (!value) return { ok: false, why: "probe returned nothing" };
    return JSON.parse(value) as Probe;
  } finally {
    try { ws.close(); } catch { /* already closed */ }
  }
}

const def: GateDefinition = {
  id: "g8",
  title: "Uptime Kuma origin check through a real browser",
  question:
    "Does a real browser's WebSocket survive Uptime Kuma's Origin check behind previewUrl (Q20), " +
    "given that Node cannot send an Origin header and therefore cannot test the branch that rejects one?",
  estimate: (plan) =>
    estimate(plan, [
      { sandboxSeconds: 180, size: SIZE_SMALL },
      { browserSeconds: 120 },
    ]),
  minObservations: 1,
  observationUnit: "browser handshake through previewUrl",
  ceilingUsd: 0.02,
  preflight: () => {
    const snap = loadRegistry().uptimekuma;
    return snap ? null : "No uptimekuma snapshot in the registry. Build it first with npm run snapshot:uptime-kuma.";
  },

  async run(ctx: GateContext) {
    const snapshotId = loadRegistry().uptimekuma!;
    const bornAt = performance.now();
    let sandboxId: string | null = null;
    let sessionId: string | null = null;

    try {
      const sb = await ctx.adapter.createSandbox(
        ctx.apiKey, "g8",
        { fromSnapshot: snapshotId, cpu: SIZE_SMALL.cpu, memMb: SIZE_SMALL.memMb,
          timeoutMs: 600_000, lifecycle: { onTimeout: "kill" } },
        0.01,
      );
      sandboxId = sb.value.sandboxId;
      const sh = (c: string, o?: { timeoutMs?: number }) => ctx.adapter.exec(ctx.apiKey, sb.value, "g8", c, o);

      const h = await waitHealthyInGuest(sh, KUMA_PORT, "/", { timeoutMs: 90_000, intervalMs: 500 });
      if (!h.ok) throw new Error("forked Uptime Kuma never became healthy");
      safeOut(`  forked instance healthy in ${h.ms} ms\n`);

      const pv = await ctx.adapter.previewUrl(ctx.apiKey, sb.value, "g8", KUMA_PORT);
      const previewUrl = pv.value.url;

      // One browser. Q20 needs a real Origin header, not twelve of them.
      const client = new Solari({ apiKey: ctx.apiKey });
      const token = ctx.ledger.browserIntent("g8", "origin check");
      const session = await client.sessions.create({});
      registerSecret(session.id);
      registerSecret(session.cdpEndpoint);
      registerSecret(session.wsEndpoint);
      sessionId = session.id;
      ctx.ledger.browserOpened(session.id, "g8", token);
      ctx.guard.openedBrowser(session.id);

      const browserStart = performance.now();
      const probe = await probeInBrowser(session.cdpEndpoint, previewUrl);
      const browserSeconds = (performance.now() - browserStart) / 1000;
      ctx.guard.addBrowserSeconds(browserSeconds, true, "one browser session, observed elapsed");

      safeOut(`  browser origin: ${probe.origin ?? "unknown"}\n`);
      safeOut(`  result: ${probe.ok ? "ADMITTED" : "REJECTED"} (${probe.why})\n`);

      const verdict = probe.ok
        ? `Q20 RESOLVED POSITIVE. A real Chromium page loaded from the preview origin opened a WebSocket to ` +
          `Uptime Kuma and received an engine.io OPEN packet. The browser supplied the Origin header itself, so ` +
          `the branch that V68 could not reach, origin present and compared against Host, was exercised and passed. ` +
          `The preview domain presents Host and Origin consistently to the guest. Uptime Kuma is shippable as a ` +
          `catalog card without disabling its origin check.`
        : `Q20 RESOLVED NEGATIVE. A real Chromium page loaded from the preview origin was REJECTED: ${probe.why}. ` +
          `Node's origin-less handshake passed (V68) because Uptime Kuma explicitly allows a WebSocket with no ` +
          `Origin, so the two results are consistent and the browser one is the one that matters. This is a finding ` +
          `about running an origin-checking app behind a preview domain, and it is reported to Solari rather than ` +
          `worked around: the available workaround, UPTIME_KUMA_WS_ORIGIN_CHECK=bypass, disables a cross-site ` +
          `websocket hijacking defence to make a demo work. Uptime Kuma does not ship as a card until this is resolved.`;

      return {
        verdict,
        observations: 1,
        markdown: [
          `## What was asked`,
          ``,
          `A real Chromium page was navigated to the instance's \`previewUrl\`, so the page origin IS the preview`,
          `host, and the WebSocket was opened from inside that page. The \`Origin\` header was therefore generated by`,
          `Chromium rather than by us, which is the only way to exercise the branch that matters.`,
          ``,
          `## Why V68 was not enough`,
          ``,
          `Uptime Kuma's \`allowRequest\` permits polling unconditionally, permits a WebSocket with **no** Origin`,
          `header explicitly, and otherwise requires \`origin.host === req.headers.host\`. Node's \`WebSocket\` sends no`,
          `Origin and offers no way to set one, so V68 took the allowed-with-no-origin branch. The check that would`,
          `reject a browser was the one that probe could not trigger.`,
          ``,
          `| | |`,
          `|---|---|`,
          `| page origin | \`${probe.origin ?? "unknown"}\` |`,
          `| admitted | ${probe.ok ? "yes" : "**no**"} |`,
          `| reason | ${probe.why} |`,
          `| fork to healthy | ${h.ms} ms |`,
          `| bypass flag used | no, deliberately |`,
          ``,
          `The workaround \`UPTIME_KUMA_WS_ORIGIN_CHECK=bypass\` was not used. It disables a cross-site websocket`,
          `hijacking defence, and turning off a security control to make a demo work is how a demo becomes the`,
          `reason for an incident.`,
        ].join("\n"),
        data: {
          question: "Q20",
          previewOrigin: probe.origin ?? null,
          admitted: probe.ok,
          why: probe.why,
          firstFrame: probe.frame ?? null,
          forkToHealthyMs: h.ms,
          browserSeconds: Math.round(browserSeconds * 10) / 10,
          session: handleFor(session.id),
          bypassFlagUsed: false,
        },
      };
    } finally {
      if (sessionId) {
        try { await new Solari({ apiKey: ctx.apiKey }).sessions.releaseAndWait(sessionId); } catch { /* sweeper has it */ }
        ctx.ledger.browserClosed(sessionId);
      }
      if (sandboxId) {
        await ctx.adapter.killQuiet(ctx.apiKey, sandboxId, "g8");
        ctx.guard.addSandboxSeconds((performance.now() - bornAt) / 1000, SIZE_SMALL, true, "g8 target sandbox");
      }
    }
  },
};

export default def;

if (process.argv[1] && import.meta.url.endsWith(process.argv[1].split("/").pop() ?? "")) {
  process.exit(await runGate(def));
}
